/*
====================================================
Retail Sales Analytics
Business Queries
Author: Anitta Kurian
====================================================
*/


/*
Business Question 1

What is the total sales revenue generated by the company?
*/

SELECT
ROUND(SUM(sales),2) AS Total_Sales
FROM retail_sales;


/*
Business Question 2

What is the total profit generated by the company?
*/

SELECT
ROUND(SUM(profit),2) AS Total_Profit
FROM retail_sales;


/*
Business Question 3

How many orders were placed?
*/

SELECT
COUNT(DISTINCT order_id) AS Total_Orders
FROM retail_sales;


/*
Business Question 4

How many unique customers are there?
*/

SELECT
COUNT(DISTINCT customer_id) AS Total_Customers
FROM retail_sales;

/*
Business Question 5

What is the average sales per order?
*/

SELECT
ROUND(AVG(sales),2) AS Average_Order_Value
FROM retail_sales;