/*
====================================================
Retail Sales Analytics
Business Queries
Author: Anitta Kurian
====================================================
*/


/*
Business Question 1

What is the total sales revenue generated by the company?
*/

SELECT
ROUND(SUM(sales),2) AS Total_Sales
FROM retail_sales;


/*
Business Question 2

What is the total profit generated by the company?
*/

SELECT
ROUND(SUM(profit),2) AS Total_Profit
FROM retail_sales;


/*
Business Question 3

How many orders were placed?
*/

SELECT
COUNT(DISTINCT order_id) AS Total_Orders
FROM retail_sales;


/*
Business Question 4

How many unique customers are there?
*/

SELECT
COUNT(DISTINCT customer_id) AS Total_Customers
FROM retail_sales;

/*
Business Question 5

What is the average sales per order?
*/

SELECT
ROUND(AVG(sales),2) AS Average_Order_Value
FROM retail_sales;

/*
Business Question 6

 How many total products were sold?
*/

SELECT
    SUM(quantity) AS total_quantity_sold
FROM retail_sales;

/*
Business Question 7

What is the average profit per transaction?
*/

SELECT
    ROUND(AVG(profit), 2) AS average_profit
FROM retail_sales;
/*
Business Question 8

What is the company's profit margin (%)?
Formula:
(Total Profit / Total Sales) × 100
*/
SELECT
    ROUND((SUM(profit) / SUM(sales)) * 100, 2) AS profit_margin_percentage
FROM retail_sales;

/*
Business Question 9

How many different products does the company sell?
*/
SELECT
    COUNT(DISTINCT product_id) AS unique_products
FROM retail_sales;

/*
Business Question 10

How many product categories and sub-categories are available?
*/
SELECT
    COUNT(DISTINCT category) AS total_categories,
    COUNT(DISTINCT sub_category) AS total_sub_categories
FROM retail_sales;